### ISSUE TITLE
Please, fix chashing while tapping on row header

### ISSUE THREAD

**Issue by yurevich1** [glyuck/GlyuckDataGrid#2]
Inside this class
`public class DataGridViewBaseHeaderCell: DataGridViewBaseCell {`

change function

`public func didTap(gesture: UITapGestureRecognizer) {
        dataGridView.collectionViewDelegate.collectionView(dataGridView.collectionView, didTapHeaderForColumn: indexPath.row)
    }`

into

```
public func didTap(gesture: UITapGestureRecognizer) {
        dataGridView.collectionViewDelegate.collectionView(dataGridView.collectionView, didTapHeaderForColumn: indexPath.index)
    }
```

if use the fisrt variant the library crashes with

> Assertion failure in -[NSIndexPath row]

**Comment by glyuck** [comment]
Fixed it in master, forgot to publish a new release. Done now: v0.2.1.
