### ISSUE TITLE
issues with obj-c implementation

### ISSUE THREAD

**Issue by multinerd** [glyuck/GlyuckDataGrid#8]
im making progress on my own implemtation, however i am unable to access `indexPath.dataGridColumn` in objective c

**Comment by multinerd** [comment]
im making progress on my own implemtation, however i am unable to access `indexPath.dataGridColumn` in objective c

**Comment by glyuck** [comment]
It's because these properties are defined in `IndexPath` extension, it's a swift overlay for `NSIndexPath` class. I've duplicated this extension for `NSIndexPath` and added Objective-C example.

**Comment by multinerd** [comment]
thank you very much. one of these days i'm gonna jump on the swift train... that day is just not today
